package civ.model.Units;

public enum Actions {
    ACTION_MOVE,
    ACTION_DESTROY,
    ACTION_CREATE_FORT,
    ACTION_CREATE_FARM,
    ACTION_CREATE_CITY,
    ACTION_KILL_THIS_UNIT,
    ACTION_KILL_FIRSTFIGHTER,
    ACTION_KILL_SECONDFIGHTER,
    ACTION_KILL_THIRDFIGHTER,
    ACTION_KILL_POSELENEC,
    ACTION_KILL_WORKER,
    ACTION_KILL_SHIP,
    ACTION_DESTROY_CITY,
    ACTION_EXPLORE
}
